apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "terra.terra-rebels.org/v1alpha1",
          "kind": "TerradNode",
          "metadata": {
            "name": "terradnode-sample"
          },
          "spec": {
            "nodeImage": "toban/classic-core"
          }
        },
        {
          "apiVersion": "terra.terra-rebels.org/v1alpha1",
          "kind": "Validator",
          "metadata": {
            "name": "validator-sample"
          },
          "spec": {
            "chainId": "columbus-5",
            "commissionChangeRate": "0.01",
            "fromKeyName": "tmp",
            "initialCommissionRate": "0.20",
            "initialSelfBondAmount": "5000000",
            "isPublic": true,
            "maximumCommission": "1.00",
            "minimumSelfBondAmount": "1",
            "name": "my-epic-validator",
            "nodeImage": "toban/classic-core"
          }
        }
      ]
    capabilities: Basic Install
    operators.operatorframework.io/builder: operator-sdk-v1.21.0
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v3
  name: terra-operator.v0.0.1
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: TerradNode is the Schema for the terradnodes API
      displayName: Terrad Node
      kind: TerradNode
      name: terradnodes.terra.terra-rebels.org
      version: v1alpha1
    - description: Validator is the Schema for the validators API
      displayName: Validator
      kind: Validator
      name: validators.terra.terra-rebels.org
      version: v1alpha1
  description: terra-operator
  displayName: terra-operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - terra.terra-rebels.org
          resources:
          - terradnodes
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - terra.terra-rebels.org
          resources:
          - terradnodes/finalizers
          verbs:
          - update
        - apiGroups:
          - terra.terra-rebels.org
          resources:
          - terradnodes/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - terra.terra-rebels.org
          resources:
          - validators
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - terra.terra-rebels.org
          resources:
          - validators/finalizers
          verbs:
          - update
        - apiGroups:
          - terra.terra-rebels.org
          resources:
          - validators/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - ""
          resources:
          - pods
          - services
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - authentication.k8s.io
          resources:
          - tokenreviews
          verbs:
          - create
        - apiGroups:
          - authorization.k8s.io
          resources:
          - subjectaccessreviews
          verbs:
          - create
        serviceAccountName: terra-operator-controller-manager
      deployments:
      - label:
          control-plane: controller-manager
        name: terra-operator-controller-manager
        spec:
          replicas: 1
          selector:
            matchLabels:
              control-plane: controller-manager
          strategy: {}
          template:
            metadata:
              annotations:
                kubectl.kubernetes.io/default-container: manager
              labels:
                control-plane: controller-manager
            spec:
              containers:
              - args:
                - --secure-listen-address=0.0.0.0:8443
                - --upstream=http://127.0.0.1:8080/
                - --logtostderr=true
                - --v=0
                image: gcr.io/kubebuilder/kube-rbac-proxy:v0.11.0
                name: kube-rbac-proxy
                ports:
                - containerPort: 8443
                  name: https
                  protocol: TCP
                resources:
                  limits:
                    cpu: 500m
                    memory: 128Mi
                  requests:
                    cpu: 5m
                    memory: 64Mi
              - args:
                - --health-probe-bind-address=:8081
                - --metrics-bind-address=127.0.0.1:8080
                - --leader-elect
                command:
                - /manager
                image: toban/terra-operator:0.0.1
                livenessProbe:
                  httpGet:
                    path: /healthz
                    port: 8081
                  initialDelaySeconds: 15
                  periodSeconds: 20
                name: manager
                readinessProbe:
                  httpGet:
                    path: /readyz
                    port: 8081
                  initialDelaySeconds: 5
                  periodSeconds: 10
                resources:
                  limits:
                    cpu: 500m
                    memory: 128Mi
                  requests:
                    cpu: 10m
                    memory: 64Mi
                securityContext:
                  allowPrivilegeEscalation: false
              securityContext:
                runAsNonRoot: true
              serviceAccountName: terra-operator-controller-manager
              terminationGracePeriodSeconds: 10
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - coordination.k8s.io
          resources:
          - leases
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        serviceAccountName: terra-operator-controller-manager
    strategy: deployment
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - Terra v1
  - Terra v2
  links:
  - name: Terra Operator
    url: https://terra-operator.domain
  maturity: alpha
  provider:
    name: terra-operator
  version: 0.0.1
