apiVersion: batch/v1 
kind: Job 
metadata:   
  name: localnet-harkonnen-setup
spec:
  backoffLimit: 3  
  ttlSecondsAfterFinished: 0
  template:
    spec:       
      containers:       
      - name: localnet-harkonnen-setup      
        image: public.ecr.aws/p5q2r9h7/node:alpine3.17
        imagePullPolicy: Always
        command: ["/bin/sh", "/setup-localnet.sh"]
        volumeMounts:
        - name: job-volume
          mountPath: /terra
        env:
        - name: CHAINID
          value: harkonnen
        - name: REPLICA
          value: "7"
      restartPolicy: Never
      volumes:
      - name: job-volume
        persistentVolumeClaim:
          claimName: harkonnen-config