apiVersion: terra.terra-rebels.org/v1alpha1
kind: TerradNet
metadata:
  name: harkonnen
spec:
  container:
    image: public.ecr.aws/classic-terra/node:alpine3.17
    imagePullPolicy: Always
  chainId: harkonnen
  serviceName: harkonnen-service
  dataSource:
    name: data-source
    persistentVolumeClaim:
      claimName: harkonnen-config
