# permissions for end users to view indexernodes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: indexernode-viewer-role
rules:
- apiGroups:
  - terra.terra-rebels.org
  resources:
  - indexernodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - terra.terra-rebels.org
  resources:
  - indexernodes/status
  verbs:
  - get
