# permissions for end users to view oraclenodes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: oraclenode-viewer-role
rules:
- apiGroups:
  - terra.terra-rebels.org
  resources:
  - oraclenodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - terra.terra-rebels.org
  resources:
  - oraclenodes/status
  verbs:
  - get
