# permissions for end users to edit oraclefeeders.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: oraclefeeder-editor-role
rules:
- apiGroups:
  - terra.terra-rebels.org
  resources:
  - oraclefeeders
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - terra.terra-rebels.org
  resources:
  - oraclefeeders/status
  verbs:
  - get
