# permissions for end users to edit oraclenodes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: oraclenode-editor-role
rules:
- apiGroups:
  - terra.terra-rebels.org
  resources:
  - oraclenodes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - terra.terra-rebels.org
  resources:
  - oraclenodes/status
  verbs:
  - get
