---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - terra.terra-rebels.org
  resources:
  - relayers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - terra.terra-rebels.org
  resources:
  - relayers/finalizers
  verbs:
  - update
- apiGroups:
  - terra.terra-rebels.org
  resources:
  - relayers/status
  verbs:
  - get
  - patch
  - update
