---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - terra.terra-rebels.org
  resources:
  - terradnodes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - terra.terra-rebels.org
  resources:
  - terradnodes/finalizers
  verbs:
  - update
- apiGroups:
  - terra.terra-rebels.org
  resources:
  - terradnodes/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - terra.terra-rebels.org
  resources:
  - validators
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - terra.terra-rebels.org
  resources:
  - validators/finalizers
  verbs:
  - update
- apiGroups:
  - terra.terra-rebels.org
  resources:
  - validators/status
  verbs:
  - get
  - patch
  - update
- apiGroups: [""]
  resources:
  - pods
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
