# permissions for end users to edit terradnodes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: terradnode-editor-role
rules:
- apiGroups:
  - terra.terra-rebels.org
  resources:
  - terradnodes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - terra.terra-rebels.org
  resources:
  - terradnodes/status
  verbs:
  - get
