# permissions for end users to view terradnodes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: terradnode-viewer-role
rules:
- apiGroups:
  - terra.terra-rebels.org
  resources:
  - terradnodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - terra.terra-rebels.org
  resources:
  - terradnodes/status
  verbs:
  - get
