# permissions for end users to view validators.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: validator-viewer-role
rules:
- apiGroups:
  - terra.terra-rebels.org
  resources:
  - validators
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - terra.terra-rebels.org
  resources:
  - validators/status
  verbs:
  - get
