apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: terradnodes.terra.rebels.info
spec:
  group: terra.rebels.info
  names:
    kind: TerradNode
    listKind: TerradNodeList
    plural: terradnodes
    singular: terradnode
  scope: Namespaced
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:    
      openAPIV3Schema:
        description: TerradNode is the Schema for the terradnodes API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          envFrom:
            items:
              description: EnvFromSource represents the source of a set of ConfigMaps
              properties:
                configMapRef:
                  description: The ConfigMap to select from
                  properties:
                    name:
                      description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                        TODO: Add other useful fields. apiVersion, kind, uid?'
                      type: string
                    optional:
                      description: Specify whether the ConfigMap must be defined
                      type: boolean
                  type: object
                prefix:
                  description: An optional identifier to prepend to each key in the
                    ConfigMap. Must be a C_IDENTIFIER.
                  type: string
                secretRef:
                  description: The Secret to select from
                  properties:
                    name:
                      description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                        TODO: Add other useful fields. apiVersion, kind, uid?'
                      type: string
                    optional:
                      description: Specify whether the Secret must be defined
                      type: boolean
                  type: object
              type: object
            type: array
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: TerradNodeSpec defines the desired state of TerradNode
            properties:
              address:
                type: string
              commissionChangeRate:
                type: string
              description:
                type: string
              initialCommissionRate:
                type: string
              initialSelfBondAmount:
                type: string
              maximumCommission:
                type: string
              minimumSelfBondAmount:
                type: string
              name:
                type: string
              pubKey:
                description: 'Important: Run "operator-sdk generate k8s" to regenerate
                  code after modifying this file Important: Run "operator-sdk generate
                  crds" to regenerate crds after modifying this file Add custom validation
                  using kubebuilder tags: https://book-v1.book.kubebuilder.io/beyond_basics/generating_crd.html'
                type: string
              website:
                type: string
            required:
            - address
            - commissionChangeRate
            - initialCommissionRate
            - initialSelfBondAmount
            - maximumCommission
            - minimumSelfBondAmount
            - name
            - pubKey
            type: object
          status:
            description: TerradNodeStatus defines the observed state of TerradNode
            type: object
        type: object 
    subresources:
      status: {}
