apiVersion: terra.terra-rebels.org/v1alpha1
kind: TerradNode
metadata:
  name: harkonnen
spec:
  container:
    image: public.ecr.aws/p5q2r9h7/node:alpine3.17
    imagePullPolicy: Always
  chainId: harkonnen
  isNewNetwork: true