version: '3.8'

services:
  relayer:
    image: classic-terra/relayer
    build:
      context: relayer
      dockerfile: Dockerfile
      platforms:
        - "linux/amd64"
      labels:
        - "classic-terra/relayer description=ibc relayer"