kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: terra-operator
  namespace: terra
subjects:
- kind: ServiceAccount
  name: terra-operator
roleRef:
  kind: Role
  name: terra-operator
  apiGroup: rbac.authorization.k8s.io
