apiVersion: terra.terra-rebels.org/v1alpha1
kind: Validator
metadata:
  name: validator-sample
spec:
  chainId: columbus-5
  terradNodeImage: toban/classic-core-node:v0.5.11-oracle
  oracleFeederNodeImage: toban/classic-core-node-oraclefeeder:v0.5.11-oracle
  passphrase: tmp12345
  mnenomic: words are really fun to play with
  initialCommissionRate: "0.20"
  maximumCommission: "1.00"
  commissionChangeRate: "0.01"
  minimumSelfBondAmount: "1"
  initialSelfBondAmount: "5000000"
  isPublic: true
