apiVersion: terra.terra-rebels.org/v1alpha1
kind: Relayer
metadata:
  labels:
    app.kubernetes.io/name: relayer
    app.kubernetes.io/instance: relayer-sample
    app.kubernetes.io/part-of: terra-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: terra-operator
  name: relayer-sample
spec:
  # TODO(user): Add fields here
