apiVersion: terra.terra-rebels.org/v1alpha1
kind: Validator
metadata:
  name: validator-sample
spec:
  terradNodeImage: terrarebels/terraclassic.terrad-node:latest-rebel-1 
  oracleNodeImage: terrarebels/terraclassic.oracle-node:latest-rebel-1
  chainId: columbus-1
  passphrase: "12345678"
  mnenomic: torch swamp cancel lift never october child harsh rib aspect luxury word peanut length bamboo hawk material vehicle glue above west random sketch author  
  amount: 1uluna
  commissionRate: "0.20"
  commissionRateMax: "1.00"
  commissionRateMaxChange: "0.01"
  minimumSelfDelegation: "1"
  isPublic: true
  autoConfig: true