# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/terra.terra-rebels.org_terradnodes.yaml
- bases/terra.terra-rebels.org_validators.yaml
- bases/terra.terra-rebels.org_oraclenodes.yaml
- bases/terra.terra-rebels.org_indexernodes.yaml
- bases/terra.terra-rebels.org_relayers.yaml
- bases/terra.terra-rebels.org_terranetdeployments.yaml
#+kubebuilder:scaffold:crdkustomizeresource

patchesStrategicMerge:
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
#- patches/webhook_in_terradnodes.yaml
#- patches/webhook_in_validators.yaml
#- patches/webhook_in_oraclenodes.yaml
#- patches/webhook_in_indexernodes.yaml
#- patches/webhook_in_relayers.yaml
#- patches/webhook_in_terranetdeployments.yaml
#+kubebuilder:scaffold:crdkustomizewebhookpatch

# [CERTMANAGER] To enable cert-manager, uncomment all the sections with [CERTMANAGER] prefix.
# patches here are for enabling the CA injection for each CRD
#- patches/cainjection_in_terradnodes.yaml
#- patches/cainjection_in_validators.yaml
#- patches/cainjection_in_oraclenodes.yaml
#- patches/cainjection_in_indexernodes.yaml
#- patches/cainjection_in_relayers.yaml
#- patches/cainjection_in_terranetdeployments.yaml
#+kubebuilder:scaffold:crdkustomizecainjectionpatch

# the following config is for teaching kustomize how to do kustomization for CRDs.
configurations:
- kustomizeconfig.yaml
