apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
  - name: my-container
    image: alpine
    command: ["/bin/sh", "-c", "while true; do echo 'Hello, world!'; sleep 10; done"]
    volumeMounts:
    - name: my-volume
      mountPath: /terra
  volumes:
  - name: my-volume
    persistentVolumeClaim:
      claimName: node-data-atreides-0
